[package]
name = "chess"
version = "0.1.0"
authors = ["Felix Chapman <aelred717@gmail.com>"]
edition = "2018"

[dependencies]
enum-map = "0.4.1"
lazy_static = "1.2.0"
rand = "0.6.1"
array-init = "0.0.4"
chashmap = "2.2.0"

[dev-dependencies]
pretty_assertions = "0.5.1"

[features]
# Makes warnings into errors
strict = []

[profile.release]
debug = true