name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true
    - run: make build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true
    - run: make deploy
